services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./static/audio:/app/static/audio
      - ./static/images:/app/static/images
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    environment:
      - DEBUG=True