# Generated by Django 5.1 on 2025-08-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название (например, Утка)')),
                ('sound', models.FileField(upload_to='sounds/', verbose_name='Аудиофайл')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
            ],
        ),
    ]
